### ISSUE TITLE
Text inputs disappear if wrong type of consent chosen 

### ISSUE THREAD

**Issue by keithiopia** [cds-snc/simplify-privacy-statements-V2#90]
How to replicate:
Put answers in all the free text fields, answer 'yes' to the compensation question, and answer 'Verbally' to the consent question. On pressing 'Continue' the correct error message appears, but all the text fields other than 'Name', 'Phone' and 'Email' are wiped clear.

**Comment by sastels** [comment]
So this is because of #89 essentially. After validation the language variable isn't defined, so it tries to use fields like `research_goal` instead of `research_goal_en` or `research_goal_fr`.

I've talked to Tim a bit and he had a workaround to exactly this that he used in another app, I'll probably spend tomorrow seeing if I can get this workaround working in our app.

**Comment by sastels** [comment]
fixed by #99
